#!/usr/bin/env python3
"""
build_pr_body.py - Generates the PR title and markdown body from a diff report.

Usage:
  python3 build_pr_body.py <diff_report.json> <old_version> <new_version>
                           <new_date> <spec_commit>
                           <title_output.txt> <body_output.md>
"""

import datetime
import json
import sys


def emoji_for_count(count):
    if count == 0:
        return "➖"
    return "✅"


def fmt_list(items, limit=50, code=True):
    if not items:
        return "_None_\n"
    wrap = "`" if code else ""
    lines = [f"- {wrap}{i}{wrap}" for i in items[:limit]]
    if len(items) > limit:
        lines.append(f"- ...and **{len(items) - limit}** more")
    return "\n".join(lines) + "\n"


def fmt_changed(items_dict, limit=30):
    if not items_dict:
        return "_None_\n"
    lines = []
    for i, (name, changes) in enumerate(list(items_dict.items())[:limit]):
        lines.append(f"<details><summary><code>{name}</code> ({len(changes)} change(s))</summary>\n")
        lines.append("\n")
        for field, desc in changes.items():
            lines.append(f"- **`{field}`**: {desc}\n")
        lines.append("\n</details>\n")
    if len(items_dict) > limit:
        lines.append(f"\n_...and {len(items_dict) - limit} more changed items_\n")
    return "".join(lines)


def main():
    if len(sys.argv) < 8:
        print("Usage: build_pr_body.py <report.json> <old_v> <new_v> <date> <commit> <title.txt> <body.md>")
        sys.exit(1)

    report = json.load(open(sys.argv[1]))
    old_v = sys.argv[2]
    new_v = sys.argv[3]
    new_d = sys.argv[4]
    commit = sys.argv[5]
    title_out = sys.argv[6]
    body_out = sys.argv[7]

    added_types = report.get("added_types", [])
    removed_types = report.get("removed_types", [])
    changed_types = report.get("changed_types", {})
    added_methods = report.get("added_methods", [])
    removed_methods = report.get("removed_methods", [])
    changed_methods = report.get("changed_methods", {})
    stats = report.get("stats", {})

    # Determine if this is a breaking change
    is_breaking = bool(removed_types or removed_methods)
    breaking_label = "⚠️ BREAKING" if is_breaking else "✨"

    # Build title - old_v/new_v already contain "Bot API X.X", don't prepend again
    title = f"🤖 {breaking_label} {old_v} → {new_v} - Auto-regenerated"
    with open(title_out, "w") as f:
        f.write(title)

    # Build body
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    spec_url = f"https://github.com/tgapis/x/commit/{commit}"
    changelog_url = "https://core.telegram.org/bots/api#recent-changes"

    body = f"""## 🤖 Telegram Bot API Update: `{old_v}` → `{new_v}`

> **Auto-generated by the [codegen workflow](.github/workflows/auto-regenerate.yml)**  
> Generated at: {now}

---

### 📋 Summary

| | Before | After | Delta |
|---|---|---|---|
| **API Version** | `{old_v}` | `{new_v}` ({new_d}) | - |
| **Types** | {stats.get('old_types', '?')} | {stats.get('new_types', '?')} | {emoji_for_count(len(added_types))} +{len(added_types)} / ❌ -{len(removed_types)} |
| **Methods** | {stats.get('old_methods', '?')} | {stats.get('new_methods', '?')} | {emoji_for_count(len(added_methods))} +{len(added_methods)} / ❌ -{len(removed_methods)} |
| **Changed Types** | - | - | 🔄 {len(changed_types)} |
| **Changed Methods** | - | - | 🔄 {len(changed_methods)} |

🔗 [Official Changelog]({changelog_url}) | [Spec Commit]({spec_url})

---

"""

    if is_breaking:
        body += f"""### ⚠️ Breaking Changes

This update contains **removed types/methods** which may require manual review before merging.

"""

    # New Types
    body += f"### ✅ New Types ({len(added_types)})\n\n"
    body += fmt_list(added_types)
    body += "\n"

    # Removed Types
    body += f"### ❌ Removed Types ({len(removed_types)})\n\n"
    body += fmt_list(removed_types)
    body += "\n"

    # New Methods
    body += f"### ✅ New Methods ({len(added_methods)})\n\n"
    body += fmt_list(added_methods)
    body += "\n"

    # Removed Methods
    body += f"### ❌ Removed Methods ({len(removed_methods)})\n\n"
    body += fmt_list(removed_methods)
    body += "\n"

    # Changed Types (collapsible)
    body += f"### 🔄 Changed Types ({len(changed_types)})\n\n"
    body += fmt_changed(changed_types)
    body += "\n"

    # Changed Methods (collapsible)
    body += f"### 🔄 Changed Methods ({len(changed_methods)})\n\n"
    body += fmt_changed(changed_methods)
    body += "\n"

    body += f"""---

### 🔧 Files Changed

| File | Description |
|---|---|
| `api.json` | Updated Telegram Bot API spec |
| `spec_commit` | Pinned spec commit SHA |
| `tgbotrs/src/gen_types.rs` | Auto-generated type definitions |
| `tgbotrs/src/gen_methods.rs` | Auto-generated method implementations |

### ✅ Checklist

- [x] API spec fetched from `{spec_url[:60]}...`
- [x] Codegen ran successfully
- [x] All {stats.get('new_types', '?')} types generated
- [x] All {stats.get('new_methods', '?')} methods generated
- [x] Validation script passed
- [ ] Manual review (required for breaking changes)
- [ ] Tests pass in CI

---
_This PR was created automatically. Merge to publish a new crate version._
"""

    with open(body_out, "w") as f:
        f.write(body)

    print(f"PR title: {title}")
    print(f"PR body written to: {body_out} ({len(body)} chars)")


if __name__ == "__main__":
    main()
