"""
hand_crafted_types.py — Single source of truth for types that are
implemented manually in the library rather than auto-generated by codegen.

These types are SKIPPED by codegen/codegen.py (to avoid duplicates)
and EXEMPTED from the gen_types.rs check in validate_generated.py
(but still validated to exist somewhere in the source tree).

To add a new hand-crafted type:
  1. Implement it in the appropriate src/*.rs file
  2. Re-export it from lib.rs if needed
  3. Add its name to HAND_CRAFTED_TYPES below
  4. Add the file(s) where it lives to HAND_CRAFTED_SOURCE_FILES
"""

# Types whose definitions live outside gen_types.rs.
# Keys = type name, Values = list of source files that define them.
HAND_CRAFTED_TYPES = {
    # Defined in tgbotrs/src/input_file.rs
    "InputFile":  ["tgbotrs/src/input_file.rs"],
    # Defined in tgbotrs/src/lib.rs  (ergonomic wrapper with From<> impls)
    "InputMedia": ["tgbotrs/src/lib.rs"],
}
